### PR TITLE
Little Big Update exception Handled and QMM loading fix 

### PR DESCRIPTION
**Pull request by MrPurple6411**

### CODE REVIEW

**Comment by MarcoRauscher** [comment]
Thank you for the effort.
Could you also build the project and commit the binary files to Releases\FishOverflowDistributor\1.0.1 ? I would then upload to Nexus.

And please revert the changes to "FishOverflowDistributor.csproj" .. including machine-specific paths in the repository is not a good idea.

**Comment by MrPurple6411** [comment]
Will fix and do that.... sorry did not notice this reply.

**Comment by MrPurple6411** [comment]
@MarcoRauscher I think I got it all.... I do have one more question... i noticed on Nexus Mods it says I can update and stuff but says not to port to other games. I was hoping to make this work on Below Zero if you would be good with that. I would make it on a new Below Zero branch and submit a pull request when it was working and you could release it.

**Comment by MarcoRauscher** [comment]
@MrPurple6411 I have uploaded the binaries to Nexus.

As I didn't think of Below Zero when I created the mod, I did not include the permission. I have updated the permissions on Nexus now. As I don't play the game anymore, you are free to take over the mod completely for both Subnautica and Below Zero, if you want to do that :) If you tell me your Nexus user name I can add you as an editor to the mod, or you can upload your own file.

**Comment by MrPurple6411** [comment]
My nexus is also MrPurple6411 same as my github. and thank you I will begin working on Below Zero shortly.

**Pull request merged**
